# https://taskfile.dev
version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: install
      - task: lint
      - task: test

  install:
    desc: Install dependencies.
    cmds:
      - poetry install

  fix:
    desc: Run linting and fix issues.
    cmds:
      - poetry run ruff rubrical tests --fix

  lint:
    desc: Run linting tasks.
    cmds:
      - poetry run black .
      - poetry run ruff rubrical tests
      - poetry run mypy rubrical

  test:
    desc: Run unit and integration tests
    cmds:
      - poetry run pytest tests/unit tests/integration

  test-cov:
    desc: Run unit and integration tests with coverage
    cmds:
      - poetry run pytest --cov rubrical --cov-report term --cov-report html:test_results/cov_html --cov-report xml:test_results/cov.xml tests/unit tests/integration

  docker-build:
    desc: Builds Docker container for local testing.
    cmds:
      - docker build -t rubrical .

  docker:
    desc: Runs Rubrical in Docker container.
    cmds:
      - task: docker-build
      - docker run --rm -it --entrypoint sh --name rubrical rubrical:latest
