# https://taskfile.dev
version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: install
      - task: lint
      - task: test

  install:
    desc: Install dependencies.
    cmds:
      - poetry install

  fix:
    desc: Run linting and fix issues.
    cmds:
      - poetry run ruff rubrical tests --fix

  lint:
    desc: Run linting tasks.
    cmds:
      - poetry run ruff rubrical tests
      - poetry run mypy rubrical

  test:
    desc: Run unit and integration tests
    cmds:
      - poetry run pytest tests/unit tests/integration
