# https://taskfile.dev
version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: install
      - task: lint
      - task: test

  install:
    desc: Install dependencies.
    cmds:
      - pip install -U pip
      - pip install -U poetry
      - poetry install

  lint:
    desc: Run linting tasks.
    cmds:
      - pylint rubrical
      - pylint tests
      - mypy rubrical

  test:
    desc: Run unit and integration tests
    cmds:
      - pytest tests/unit tests/integration
