version: '3'

tasks:
  build:
    desc: Builds Docker container for local testing.
    cmds:
      - docker image rm rubrical || true
      - docker build -t rubrical .

  run:
    desc: Runs Rubrical in Docker container.
    cmds:
      - task: docker-build
      - docker run --rm -it --name rubrical -v `pwd`/tests/files:/code rubrical:latest --config /code/rubrical.yaml --target /code

  shell:
    desc: Runs Rubrical in Docker container.
    cmds:
      - task: docker-build
      - docker run --rm -it -v `pwd`/tests/files:/code --entrypoint sh --name rubrical rubrical:latest
